version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project3a
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1